select UF,MUNICIPIO,BAIRRO,LEFT(MATRICULATECNICO,2) CHAVE, MES_BA,ATIVIDADE, DATEDIFF(MINUTE,INICIOEXECUCAO,FIMEXECUCAO) TEMPO_TAREFA_EXE from CLICK_FECHADAS where SKILLS IN ('RETLOG', 'FTTHRET') and INICIOEXECUCAO>='2021-01-01'
AND ESTADO='Concluído com sucesso'

